server:
  port: 8888

spring:
  cloud:
    consul:
      host: ${DISCOVERY_SERVER_HOST:localhost}
      port: ${DISCOVERY_SERVER_PORT:8500}
      discovery:
        instanceId: ${spring.application.name}:${CONFIG_SERVER_INSTANCE_ID:${random.value}}
        tags: infrastracture
        port: ${SERVER_PORT:8888}
        hostname: ${SERVER_NAME:config-server}
    config:
      server:
        git:
          uri: git@github.com:vova-uvarov/app-configs.git
management:
  endpoints:
    web:
      exposure:
        include: "*"
